// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Decision is the outcome of a policy evaluation. Used by policy.proto and
// mirrored in audit.proto to keep audit self-contained.
type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	// Action is permitted immediately.
	Decision_ALLOW Decision = 1
	// Action is blocked; no further recourse.
	Decision_DENY Decision = 2
	// Action is held — a human reviewer must approve or reject it.
	Decision_PENDING Decision = 3
	// Action is permitted but sensitive fields must be redacted first.
	Decision_REDACT Decision = 4
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "ALLOW",
		2: "DENY",
		3: "PENDING",
		4: "REDACT",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"ALLOW":                1,
		"DENY":                 2,
		"PENDING":              3,
		"REDACT":               4,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// ActionType classifies what kind of operation the agent is attempting.
// Drives both policy rule matching and audit event categorisation.
type ActionType int32

const (
	ActionType_ACTION_UNSPECIFIED ActionType = 0
	// Call a large-language model (e.g. GPT-4o, Claude, Gemini).
	ActionType_LLM_CALL ActionType = 1
	// Invoke a tool or MCP server function.
	ActionType_TOOL_CALL ActionType = 2
	// Read, write, delete, or create a local file.
	ActionType_FILE_OPERATION ActionType = 3
	// Make an outbound network request.
	ActionType_NETWORK_CALL ActionType = 4
	// Execute a subprocess.
	ActionType_PROCESS_EXEC ActionType = 5
	// Spawn a child agent.
	ActionType_AGENT_SPAWN ActionType = 6
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "LLM_CALL",
		2: "TOOL_CALL",
		3: "FILE_OPERATION",
		4: "NETWORK_CALL",
		5: "PROCESS_EXEC",
		6: "AGENT_SPAWN",
	}
	ActionType_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"LLM_CALL":           1,
		"TOOL_CALL":          2,
		"FILE_OPERATION":     3,
		"NETWORK_CALL":       4,
		"PROCESS_EXEC":       5,
		"AGENT_SPAWN":        6,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// RiskTier classifies an agent or policy by the risk level it operates at.
type RiskTier int32

const (
	RiskTier_RISK_UNSPECIFIED RiskTier = 0
	// Low risk: log-only enforcement; no blocking.
	RiskTier_LOW RiskTier = 1
	// Medium risk: block-and-optionally-approve enforcement.
	RiskTier_MEDIUM RiskTier = 2
	// High risk: always block; human review mandatory.
	RiskTier_HIGH RiskTier = 3
	// Critical risk: immediate kill + incident escalation.
	RiskTier_CRITICAL RiskTier = 4
)

// Enum value maps for RiskTier.
var (
	RiskTier_name = map[int32]string{
		0: "RISK_UNSPECIFIED",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	RiskTier_value = map[string]int32{
		"RISK_UNSPECIFIED": 0,
		"LOW":              1,
		"MEDIUM":           2,
		"HIGH":             3,
		"CRITICAL":         4,
	}
)

func (x RiskTier) Enum() *RiskTier {
	p := new(RiskTier)
	*p = x
	return p
}

func (x RiskTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskTier) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (RiskTier) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x RiskTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskTier.Descriptor instead.
func (RiskTier) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// AgentId is a composite identity used in every gRPC message.
// Using a message (not a flat string) lets the gateway enforce org/team scoping
// and issue scoped credentials without changing downstream message shapes.
type AgentId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organisation identifier.
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Team within the organisation.
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The agent's own unique ID (DID-style; assigned at registration).
	AgentId       string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentId) Reset() {
	*x = AgentId{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentId) ProtoMessage() {}

func (x *AgentId) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentId.ProtoReflect.Descriptor instead.
func (*AgentId) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *AgentId) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *AgentId) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AgentId) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Timestamp uses Unix milliseconds for precision without proto well-known type imports.
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMs        int64                  `protobuf:"varint,1,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Timestamp) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x12assembly.common.v1\"T\n" +
	"\aAgentId\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"$\n" +
	"\tTimestamp\x12\x17\n" +
	"\aunix_ms\x18\x01 \x01(\x03R\x06unixMs*R\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\x12\b\n" +
	"\x04DENY\x10\x02\x12\v\n" +
	"\aPENDING\x10\x03\x12\n" +
	"\n" +
	"\x06REDACT\x10\x04*\x8a\x01\n" +
	"\n" +
	"ActionType\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bLLM_CALL\x10\x01\x12\r\n" +
	"\tTOOL_CALL\x10\x02\x12\x12\n" +
	"\x0eFILE_OPERATION\x10\x03\x12\x10\n" +
	"\fNETWORK_CALL\x10\x04\x12\x10\n" +
	"\fPROCESS_EXEC\x10\x05\x12\x0f\n" +
	"\vAGENT_SPAWN\x10\x06*M\n" +
	"\bRiskTier\x12\x14\n" +
	"\x10RISK_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(Decision)(0),     // 0: assembly.common.v1.Decision
	(ActionType)(0),   // 1: assembly.common.v1.ActionType
	(RiskTier)(0),     // 2: assembly.common.v1.RiskTier
	(*AgentId)(nil),   // 3: assembly.common.v1.AgentId
	(*Timestamp)(nil), // 4: assembly.common.v1.Timestamp
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
