// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: policy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyService_CheckAction_FullMethodName     = "/assembly.policy.v1.PolicyService/CheckAction"
	PolicyService_BatchCheck_FullMethodName      = "/assembly.policy.v1.PolicyService/BatchCheck"
	PolicyService_OpControlStream_FullMethodName = "/assembly.policy.v1.PolicyService/OpControlStream"
)

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyService handles path ② (runtime → gateway) — the hot path for every
// agent action. Target latency: < 5 ms p99.
//
// Consumed by: aa-runtime/src/gateway_client.rs (client side)
//
//	aa-gateway/src/policy_engine.rs   (server side)
type PolicyServiceClient interface {
	// CheckAction evaluates a single action before the agent dispatches it.
	// Called on every intercepted action — must be as fast as possible.
	CheckAction(ctx context.Context, in *CheckActionRequest, opts ...grpc.CallOption) (*CheckActionResponse, error)
	// BatchCheck pre-warms the policy cache for a set of anticipated actions.
	// Called at agent startup or when entering a new task context.
	BatchCheck(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error)
	// OpControlStream is the gateway → SDK push channel for op-lifecycle
	// signals (pause / resume / terminate). The SDK opens the stream once
	// per agent process at startup; the gateway pushes one OpControlMessage
	// per OpsRegistry transition matching the subscriber's agent_id. See
	// AAASM-1653 (PR-D of AAASM-1422); SDK-side consumers ship in PR-E
	// (Python), PR-F (Node), and PR-G (Go).
	OpControlStream(ctx context.Context, in *OpControlSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OpControlMessage], error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) CheckAction(ctx context.Context, in *CheckActionRequest, opts ...grpc.CallOption) (*CheckActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckActionResponse)
	err := c.cc.Invoke(ctx, PolicyService_CheckAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) BatchCheck(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckResponse)
	err := c.cc.Invoke(ctx, PolicyService_BatchCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) OpControlStream(ctx context.Context, in *OpControlSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OpControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicyService_ServiceDesc.Streams[0], PolicyService_OpControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpControlSubscribeRequest, OpControlMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyService_OpControlStreamClient = grpc.ServerStreamingClient[OpControlMessage]

// PolicyServiceServer is the server API for PolicyService service.
// All implementations must embed UnimplementedPolicyServiceServer
// for forward compatibility.
//
// PolicyService handles path ② (runtime → gateway) — the hot path for every
// agent action. Target latency: < 5 ms p99.
//
// Consumed by: aa-runtime/src/gateway_client.rs (client side)
//
//	aa-gateway/src/policy_engine.rs   (server side)
type PolicyServiceServer interface {
	// CheckAction evaluates a single action before the agent dispatches it.
	// Called on every intercepted action — must be as fast as possible.
	CheckAction(context.Context, *CheckActionRequest) (*CheckActionResponse, error)
	// BatchCheck pre-warms the policy cache for a set of anticipated actions.
	// Called at agent startup or when entering a new task context.
	BatchCheck(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error)
	// OpControlStream is the gateway → SDK push channel for op-lifecycle
	// signals (pause / resume / terminate). The SDK opens the stream once
	// per agent process at startup; the gateway pushes one OpControlMessage
	// per OpsRegistry transition matching the subscriber's agent_id. See
	// AAASM-1653 (PR-D of AAASM-1422); SDK-side consumers ship in PR-E
	// (Python), PR-F (Node), and PR-G (Go).
	OpControlStream(*OpControlSubscribeRequest, grpc.ServerStreamingServer[OpControlMessage]) error
	mustEmbedUnimplementedPolicyServiceServer()
}

// UnimplementedPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServiceServer struct{}

func (UnimplementedPolicyServiceServer) CheckAction(context.Context, *CheckActionRequest) (*CheckActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAction not implemented")
}
func (UnimplementedPolicyServiceServer) BatchCheck(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCheck not implemented")
}
func (UnimplementedPolicyServiceServer) OpControlStream(*OpControlSubscribeRequest, grpc.ServerStreamingServer[OpControlMessage]) error {
	return status.Error(codes.Unimplemented, "method OpControlStream not implemented")
}
func (UnimplementedPolicyServiceServer) mustEmbedUnimplementedPolicyServiceServer() {}
func (UnimplementedPolicyServiceServer) testEmbeddedByValue()                       {}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_CheckAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).CheckAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_CheckAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).CheckAction(ctx, req.(*CheckActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_BatchCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).BatchCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_BatchCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).BatchCheck(ctx, req.(*BatchCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_OpControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpControlSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolicyServiceServer).OpControlStream(m, &grpc.GenericServerStream[OpControlSubscribeRequest, OpControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyService_OpControlStreamServer = grpc.ServerStreamingServer[OpControlMessage]

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assembly.policy.v1.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAction",
			Handler:    _PolicyService_CheckAction_Handler,
		},
		{
			MethodName: "BatchCheck",
			Handler:    _PolicyService_BatchCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpControlStream",
			Handler:       _PolicyService_OpControlStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "policy.proto",
}
