// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: policy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpControlSignal classifies the lifecycle action the gateway is pushing to
// the SDK. Mirrors the OpsRegistry transitions in aa-gateway/src/ops/mod.rs.
type OpControlSignal int32

const (
	// Default — never wired; treated as a malformed message by the SDK.
	OpControlSignal_OP_CONTROL_SIGNAL_UNSPECIFIED OpControlSignal = 0
	// Operator paused the op via POST /api/v1/ops/{id}/pause. SDK should
	// cooperatively yield at the next interruption point and block on resume.
	OpControlSignal_OP_CONTROL_SIGNAL_PAUSE OpControlSignal = 1
	// Operator resumed the op via POST /api/v1/ops/{id}/resume. SDK unblocks.
	OpControlSignal_OP_CONTROL_SIGNAL_RESUME OpControlSignal = 2
	// Operator (or policy deny) terminated the op. SDK fast-fails the in-flight
	// action with an OpTerminatedError.
	OpControlSignal_OP_CONTROL_SIGNAL_TERMINATE OpControlSignal = 3
)

// Enum value maps for OpControlSignal.
var (
	OpControlSignal_name = map[int32]string{
		0: "OP_CONTROL_SIGNAL_UNSPECIFIED",
		1: "OP_CONTROL_SIGNAL_PAUSE",
		2: "OP_CONTROL_SIGNAL_RESUME",
		3: "OP_CONTROL_SIGNAL_TERMINATE",
	}
	OpControlSignal_value = map[string]int32{
		"OP_CONTROL_SIGNAL_UNSPECIFIED": 0,
		"OP_CONTROL_SIGNAL_PAUSE":       1,
		"OP_CONTROL_SIGNAL_RESUME":      2,
		"OP_CONTROL_SIGNAL_TERMINATE":   3,
	}
)

func (x OpControlSignal) Enum() *OpControlSignal {
	p := new(OpControlSignal)
	*p = x
	return p
}

func (x OpControlSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpControlSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[0].Descriptor()
}

func (OpControlSignal) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[0]
}

func (x OpControlSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpControlSignal.Descriptor instead.
func (OpControlSignal) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

type CheckActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Composite identity of the agent requesting the check.
	AgentId *AgentId `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Credential token issued at registration; validated on every call.
	CredentialToken string `protobuf:"bytes,2,opt,name=credential_token,json=credentialToken,proto3" json:"credential_token,omitempty"`
	// Run-level trace ID for distributed tracing correlation.
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Action-level span ID.
	SpanId string `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// High-level action category — determines which policy rules are evaluated.
	ActionType ActionType `protobuf:"varint,5,opt,name=action_type,json=actionType,proto3,enum=assembly.common.v1.ActionType" json:"action_type,omitempty"`
	// Detailed context for the specific action type.
	Context       *ActionContext `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckActionRequest) Reset() {
	*x = CheckActionRequest{}
	mi := &file_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckActionRequest) ProtoMessage() {}

func (x *CheckActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckActionRequest.ProtoReflect.Descriptor instead.
func (*CheckActionRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

func (x *CheckActionRequest) GetAgentId() *AgentId {
	if x != nil {
		return x.AgentId
	}
	return nil
}

func (x *CheckActionRequest) GetCredentialToken() string {
	if x != nil {
		return x.CredentialToken
	}
	return ""
}

func (x *CheckActionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CheckActionRequest) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *CheckActionRequest) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_UNSPECIFIED
}

func (x *CheckActionRequest) GetContext() *ActionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// ActionContext carries type-specific details for the action under evaluation.
// Exactly one field must be set; the populated field must match action_type.
type ActionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*ActionContext_LlmCall
	//	*ActionContext_ToolCall
	//	*ActionContext_FileOp
	//	*ActionContext_NetworkCall
	//	*ActionContext_ProcessExec
	Action        isActionContext_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionContext) Reset() {
	*x = ActionContext{}
	mi := &file_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionContext) ProtoMessage() {}

func (x *ActionContext) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionContext.ProtoReflect.Descriptor instead.
func (*ActionContext) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

func (x *ActionContext) GetAction() isActionContext_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActionContext) GetLlmCall() *LLMCallContext {
	if x != nil {
		if x, ok := x.Action.(*ActionContext_LlmCall); ok {
			return x.LlmCall
		}
	}
	return nil
}

func (x *ActionContext) GetToolCall() *ToolCallContext {
	if x != nil {
		if x, ok := x.Action.(*ActionContext_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ActionContext) GetFileOp() *FileOpContext {
	if x != nil {
		if x, ok := x.Action.(*ActionContext_FileOp); ok {
			return x.FileOp
		}
	}
	return nil
}

func (x *ActionContext) GetNetworkCall() *NetworkCallContext {
	if x != nil {
		if x, ok := x.Action.(*ActionContext_NetworkCall); ok {
			return x.NetworkCall
		}
	}
	return nil
}

func (x *ActionContext) GetProcessExec() *ProcessExecContext {
	if x != nil {
		if x, ok := x.Action.(*ActionContext_ProcessExec); ok {
			return x.ProcessExec
		}
	}
	return nil
}

type isActionContext_Action interface {
	isActionContext_Action()
}

type ActionContext_LlmCall struct {
	LlmCall *LLMCallContext `protobuf:"bytes,1,opt,name=llm_call,json=llmCall,proto3,oneof"`
}

type ActionContext_ToolCall struct {
	ToolCall *ToolCallContext `protobuf:"bytes,2,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type ActionContext_FileOp struct {
	FileOp *FileOpContext `protobuf:"bytes,3,opt,name=file_op,json=fileOp,proto3,oneof"`
}

type ActionContext_NetworkCall struct {
	NetworkCall *NetworkCallContext `protobuf:"bytes,4,opt,name=network_call,json=networkCall,proto3,oneof"`
}

type ActionContext_ProcessExec struct {
	ProcessExec *ProcessExecContext `protobuf:"bytes,5,opt,name=process_exec,json=processExec,proto3,oneof"`
}

func (*ActionContext_LlmCall) isActionContext_Action() {}

func (*ActionContext_ToolCall) isActionContext_Action() {}

func (*ActionContext_FileOp) isActionContext_Action() {}

func (*ActionContext_NetworkCall) isActionContext_Action() {}

func (*ActionContext_ProcessExec) isActionContext_Action() {}

// LLMCallContext carries details about a call to a large-language model.
type LLMCallContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model identifier (e.g. "gpt-4o", "claude-3-5-sonnet", "gemini-1.5-pro").
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Estimated prompt token count (pre-execution estimate from the SDK layer).
	PromptTokens int32 `protobuf:"varint,2,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	// Whether the SDK-layer PII scan flagged sensitive data in the prompt.
	ContainsPii   bool `protobuf:"varint,3,opt,name=contains_pii,json=containsPii,proto3" json:"contains_pii,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMCallContext) Reset() {
	*x = LLMCallContext{}
	mi := &file_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMCallContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMCallContext) ProtoMessage() {}

func (x *LLMCallContext) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMCallContext.ProtoReflect.Descriptor instead.
func (*LLMCallContext) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{2}
}

func (x *LLMCallContext) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMCallContext) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *LLMCallContext) GetContainsPii() bool {
	if x != nil {
		return x.ContainsPii
	}
	return false
}

// ToolCallContext carries details about a tool or MCP server invocation.
type ToolCallContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Registered tool name (e.g. "web_search", "run_python").
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Source system ("mcp", "langchain", "function").
	ToolSource string `protobuf:"bytes,2,opt,name=tool_source,json=toolSource,proto3" json:"tool_source,omitempty"`
	// JSON-encoded argument map; policy engine can inspect individual fields.
	ArgsJson []byte `protobuf:"bytes,3,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	// Target URL if the tool makes an HTTP request.
	TargetUrl     string `protobuf:"bytes,4,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallContext) Reset() {
	*x = ToolCallContext{}
	mi := &file_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallContext) ProtoMessage() {}

func (x *ToolCallContext) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallContext.ProtoReflect.Descriptor instead.
func (*ToolCallContext) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallContext) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallContext) GetToolSource() string {
	if x != nil {
		return x.ToolSource
	}
	return ""
}

func (x *ToolCallContext) GetArgsJson() []byte {
	if x != nil {
		return x.ArgsJson
	}
	return nil
}

func (x *ToolCallContext) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

// FileOpContext carries details about a filesystem operation.
type FileOpContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation type: "read", "write", "delete", or "create".
	Operation string `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	// Absolute path of the file being accessed.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Whether the eBPF layer flagged this path as sensitive (e.g. /etc, ~/.ssh).
	IsSensitivePath bool `protobuf:"varint,3,opt,name=is_sensitive_path,json=isSensitivePath,proto3" json:"is_sensitive_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileOpContext) Reset() {
	*x = FileOpContext{}
	mi := &file_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOpContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOpContext) ProtoMessage() {}

func (x *FileOpContext) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOpContext.ProtoReflect.Descriptor instead.
func (*FileOpContext) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{4}
}

func (x *FileOpContext) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *FileOpContext) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileOpContext) GetIsSensitivePath() bool {
	if x != nil {
		return x.IsSensitivePath
	}
	return false
}

// NetworkCallContext carries details about an outbound network request.
type NetworkCallContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target hostname.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Target port.
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Protocol: "https", "grpc", "ws", "tcp".
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Whether the target host is in the org-level network allowlist.
	InAllowlist   bool `protobuf:"varint,4,opt,name=in_allowlist,json=inAllowlist,proto3" json:"in_allowlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkCallContext) Reset() {
	*x = NetworkCallContext{}
	mi := &file_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCallContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCallContext) ProtoMessage() {}

func (x *NetworkCallContext) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCallContext.ProtoReflect.Descriptor instead.
func (*NetworkCallContext) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkCallContext) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NetworkCallContext) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NetworkCallContext) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkCallContext) GetInAllowlist() bool {
	if x != nil {
		return x.InAllowlist
	}
	return false
}

// ProcessExecContext carries details about a subprocess execution attempt.
type ProcessExecContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command to execute.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Arguments passed to the command.
	Args          []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessExecContext) Reset() {
	*x = ProcessExecContext{}
	mi := &file_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessExecContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessExecContext) ProtoMessage() {}

func (x *ProcessExecContext) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessExecContext.ProtoReflect.Descriptor instead.
func (*ProcessExecContext) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessExecContext) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProcessExecContext) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// CheckActionResponse is the policy engine's verdict for the submitted action.
type CheckActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The enforcement decision.
	Decision Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=assembly.common.v1.Decision" json:"decision,omitempty"`
	// Human-readable explanation of the decision (included in audit log).
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Identifier of the policy rule that triggered this decision.
	PolicyRule string `protobuf:"bytes,3,opt,name=policy_rule,json=policyRule,proto3" json:"policy_rule,omitempty"`
	// Populated only when decision = PENDING; identifies the approval queue item.
	ApprovalId string `protobuf:"bytes,4,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	// Populated only when decision = REDACT; describes which fields to redact.
	Redact *RedactInstructions `protobuf:"bytes,5,opt,name=redact,proto3" json:"redact,omitempty"`
	// Gateway decision latency in microseconds — used for p99 SLO monitoring.
	DecisionLatencyUs int64 `protobuf:"varint,6,opt,name=decision_latency_us,json=decisionLatencyUs,proto3" json:"decision_latency_us,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckActionResponse) Reset() {
	*x = CheckActionResponse{}
	mi := &file_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckActionResponse) ProtoMessage() {}

func (x *CheckActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckActionResponse.ProtoReflect.Descriptor instead.
func (*CheckActionResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{7}
}

func (x *CheckActionResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *CheckActionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckActionResponse) GetPolicyRule() string {
	if x != nil {
		return x.PolicyRule
	}
	return ""
}

func (x *CheckActionResponse) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *CheckActionResponse) GetRedact() *RedactInstructions {
	if x != nil {
		return x.Redact
	}
	return nil
}

func (x *CheckActionResponse) GetDecisionLatencyUs() int64 {
	if x != nil {
		return x.DecisionLatencyUs
	}
	return 0
}

// RedactInstructions lists the fields that must be redacted before the action proceeds.
type RedactInstructions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RedactRule          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactInstructions) Reset() {
	*x = RedactInstructions{}
	mi := &file_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactInstructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactInstructions) ProtoMessage() {}

func (x *RedactInstructions) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactInstructions.ProtoReflect.Descriptor instead.
func (*RedactInstructions) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{8}
}

func (x *RedactInstructions) GetRules() []*RedactRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// RedactRule specifies one field redaction to apply.
type RedactRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSONPath of the field to redact (e.g. "$.args.api_key").
	FieldPath string `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// Replacement string (e.g. "[REDACTED]", "[PII]").
	Replacement   string `protobuf:"bytes,2,opt,name=replacement,proto3" json:"replacement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactRule) Reset() {
	*x = RedactRule{}
	mi := &file_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactRule) ProtoMessage() {}

func (x *RedactRule) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactRule.ProtoReflect.Descriptor instead.
func (*RedactRule) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{9}
}

func (x *RedactRule) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *RedactRule) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

// BatchCheckRequest pre-warms the policy cache with a set of anticipated actions.
type BatchCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*CheckActionRequest  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckRequest) Reset() {
	*x = BatchCheckRequest{}
	mi := &file_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckRequest) ProtoMessage() {}

func (x *BatchCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{10}
}

func (x *BatchCheckRequest) GetRequests() []*CheckActionRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// BatchCheckResponse returns one verdict per submitted request, in order.
type BatchCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*CheckActionResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckResponse) Reset() {
	*x = BatchCheckResponse{}
	mi := &file_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckResponse) ProtoMessage() {}

func (x *BatchCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{11}
}

func (x *BatchCheckResponse) GetResponses() []*CheckActionResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

// OpControlSubscribeRequest is the unary half of OpControlStream — the SDK
// opens the stream keyed by its own agent id; the gateway sends only the
// messages whose op_id belongs to that agent.
type OpControlSubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Composite identity of the subscribing agent. Matches the agent_id on
	// its CheckActionRequests so the gateway can filter the broadcast.
	AgentId       *AgentId `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpControlSubscribeRequest) Reset() {
	*x = OpControlSubscribeRequest{}
	mi := &file_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpControlSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpControlSubscribeRequest) ProtoMessage() {}

func (x *OpControlSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpControlSubscribeRequest.ProtoReflect.Descriptor instead.
func (*OpControlSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{12}
}

func (x *OpControlSubscribeRequest) GetAgentId() *AgentId {
	if x != nil {
		return x.AgentId
	}
	return nil
}

// OpControlMessage is one push from the gateway over the OpControlStream.
// The SDK routes by op_id; sequence is a monotonic counter the SDK uses
// for at-least-once delivery dedup if the channel reconnects.
type OpControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier of the op — "{trace_id}:{span_id}", same form the
	// dashboard uses to key live-ops rows.
	OpId string `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	// The lifecycle signal to apply.
	Signal OpControlSignal `protobuf:"varint,2,opt,name=signal,proto3,enum=assembly.policy.v1.OpControlSignal" json:"signal,omitempty"`
	// Per-publisher monotonic sequence number. Restarts at 0 each gateway
	// boot; SDK consumers should treat it as advisory, not as a global
	// ordering guarantee across publishers.
	Sequence      uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpControlMessage) Reset() {
	*x = OpControlMessage{}
	mi := &file_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpControlMessage) ProtoMessage() {}

func (x *OpControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpControlMessage.ProtoReflect.Descriptor instead.
func (*OpControlMessage) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{13}
}

func (x *OpControlMessage) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *OpControlMessage) GetSignal() OpControlSignal {
	if x != nil {
		return x.Signal
	}
	return OpControlSignal_OP_CONTROL_SIGNAL_UNSPECIFIED
}

func (x *OpControlMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_policy_proto protoreflect.FileDescriptor

const file_policy_proto_rawDesc = "" +
	"\n" +
	"\fpolicy.proto\x12\x12assembly.policy.v1\x1a\fcommon.proto\"\xa9\x02\n" +
	"\x12CheckActionRequest\x126\n" +
	"\bagent_id\x18\x01 \x01(\v2\x1b.assembly.common.v1.AgentIdR\aagentId\x12)\n" +
	"\x10credential_token\x18\x02 \x01(\tR\x0fcredentialToken\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\tR\x06spanId\x12?\n" +
	"\vaction_type\x18\x05 \x01(\x0e2\x1e.assembly.common.v1.ActionTypeR\n" +
	"actionType\x12;\n" +
	"\acontext\x18\x06 \x01(\v2!.assembly.policy.v1.ActionContextR\acontext\"\xf6\x02\n" +
	"\rActionContext\x12?\n" +
	"\bllm_call\x18\x01 \x01(\v2\".assembly.policy.v1.LLMCallContextH\x00R\allmCall\x12B\n" +
	"\ttool_call\x18\x02 \x01(\v2#.assembly.policy.v1.ToolCallContextH\x00R\btoolCall\x12<\n" +
	"\afile_op\x18\x03 \x01(\v2!.assembly.policy.v1.FileOpContextH\x00R\x06fileOp\x12K\n" +
	"\fnetwork_call\x18\x04 \x01(\v2&.assembly.policy.v1.NetworkCallContextH\x00R\vnetworkCall\x12K\n" +
	"\fprocess_exec\x18\x05 \x01(\v2&.assembly.policy.v1.ProcessExecContextH\x00R\vprocessExecB\b\n" +
	"\x06action\"n\n" +
	"\x0eLLMCallContext\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12#\n" +
	"\rprompt_tokens\x18\x02 \x01(\x05R\fpromptTokens\x12!\n" +
	"\fcontains_pii\x18\x03 \x01(\bR\vcontainsPii\"\x8b\x01\n" +
	"\x0fToolCallContext\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1f\n" +
	"\vtool_source\x18\x02 \x01(\tR\n" +
	"toolSource\x12\x1b\n" +
	"\targs_json\x18\x03 \x01(\fR\bargsJson\x12\x1d\n" +
	"\n" +
	"target_url\x18\x04 \x01(\tR\ttargetUrl\"m\n" +
	"\rFileOpContext\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12*\n" +
	"\x11is_sensitive_path\x18\x03 \x01(\bR\x0fisSensitivePath\"{\n" +
	"\x12NetworkCallContext\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12!\n" +
	"\fin_allowlist\x18\x04 \x01(\bR\vinAllowlist\"B\n" +
	"\x12ProcessExecContext\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\x99\x02\n" +
	"\x13CheckActionResponse\x128\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x1c.assembly.common.v1.DecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vpolicy_rule\x18\x03 \x01(\tR\n" +
	"policyRule\x12\x1f\n" +
	"\vapproval_id\x18\x04 \x01(\tR\n" +
	"approvalId\x12>\n" +
	"\x06redact\x18\x05 \x01(\v2&.assembly.policy.v1.RedactInstructionsR\x06redact\x12.\n" +
	"\x13decision_latency_us\x18\x06 \x01(\x03R\x11decisionLatencyUs\"J\n" +
	"\x12RedactInstructions\x124\n" +
	"\x05rules\x18\x01 \x03(\v2\x1e.assembly.policy.v1.RedactRuleR\x05rules\"M\n" +
	"\n" +
	"RedactRule\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x12 \n" +
	"\vreplacement\x18\x02 \x01(\tR\vreplacement\"W\n" +
	"\x11BatchCheckRequest\x12B\n" +
	"\brequests\x18\x01 \x03(\v2&.assembly.policy.v1.CheckActionRequestR\brequests\"[\n" +
	"\x12BatchCheckResponse\x12E\n" +
	"\tresponses\x18\x01 \x03(\v2'.assembly.policy.v1.CheckActionResponseR\tresponses\"S\n" +
	"\x19OpControlSubscribeRequest\x126\n" +
	"\bagent_id\x18\x01 \x01(\v2\x1b.assembly.common.v1.AgentIdR\aagentId\"\x80\x01\n" +
	"\x10OpControlMessage\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\x12;\n" +
	"\x06signal\x18\x02 \x01(\x0e2#.assembly.policy.v1.OpControlSignalR\x06signal\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence*\x90\x01\n" +
	"\x0fOpControlSignal\x12!\n" +
	"\x1dOP_CONTROL_SIGNAL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OP_CONTROL_SIGNAL_PAUSE\x10\x01\x12\x1c\n" +
	"\x18OP_CONTROL_SIGNAL_RESUME\x10\x02\x12\x1f\n" +
	"\x1bOP_CONTROL_SIGNAL_TERMINATE\x10\x032\xb6\x02\n" +
	"\rPolicyService\x12^\n" +
	"\vCheckAction\x12&.assembly.policy.v1.CheckActionRequest\x1a'.assembly.policy.v1.CheckActionResponse\x12[\n" +
	"\n" +
	"BatchCheck\x12%.assembly.policy.v1.BatchCheckRequest\x1a&.assembly.policy.v1.BatchCheckResponse\x12h\n" +
	"\x0fOpControlStream\x12-.assembly.policy.v1.OpControlSubscribeRequest\x1a$.assembly.policy.v1.OpControlMessage0\x01b\x06proto3"

var (
	file_policy_proto_rawDescOnce sync.Once
	file_policy_proto_rawDescData []byte
)

func file_policy_proto_rawDescGZIP() []byte {
	file_policy_proto_rawDescOnce.Do(func() {
		file_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)))
	})
	return file_policy_proto_rawDescData
}

var file_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_policy_proto_goTypes = []any{
	(OpControlSignal)(0),              // 0: assembly.policy.v1.OpControlSignal
	(*CheckActionRequest)(nil),        // 1: assembly.policy.v1.CheckActionRequest
	(*ActionContext)(nil),             // 2: assembly.policy.v1.ActionContext
	(*LLMCallContext)(nil),            // 3: assembly.policy.v1.LLMCallContext
	(*ToolCallContext)(nil),           // 4: assembly.policy.v1.ToolCallContext
	(*FileOpContext)(nil),             // 5: assembly.policy.v1.FileOpContext
	(*NetworkCallContext)(nil),        // 6: assembly.policy.v1.NetworkCallContext
	(*ProcessExecContext)(nil),        // 7: assembly.policy.v1.ProcessExecContext
	(*CheckActionResponse)(nil),       // 8: assembly.policy.v1.CheckActionResponse
	(*RedactInstructions)(nil),        // 9: assembly.policy.v1.RedactInstructions
	(*RedactRule)(nil),                // 10: assembly.policy.v1.RedactRule
	(*BatchCheckRequest)(nil),         // 11: assembly.policy.v1.BatchCheckRequest
	(*BatchCheckResponse)(nil),        // 12: assembly.policy.v1.BatchCheckResponse
	(*OpControlSubscribeRequest)(nil), // 13: assembly.policy.v1.OpControlSubscribeRequest
	(*OpControlMessage)(nil),          // 14: assembly.policy.v1.OpControlMessage
	(*AgentId)(nil),                   // 15: assembly.common.v1.AgentId
	(ActionType)(0),                   // 16: assembly.common.v1.ActionType
	(Decision)(0),                     // 17: assembly.common.v1.Decision
}
var file_policy_proto_depIdxs = []int32{
	15, // 0: assembly.policy.v1.CheckActionRequest.agent_id:type_name -> assembly.common.v1.AgentId
	16, // 1: assembly.policy.v1.CheckActionRequest.action_type:type_name -> assembly.common.v1.ActionType
	2,  // 2: assembly.policy.v1.CheckActionRequest.context:type_name -> assembly.policy.v1.ActionContext
	3,  // 3: assembly.policy.v1.ActionContext.llm_call:type_name -> assembly.policy.v1.LLMCallContext
	4,  // 4: assembly.policy.v1.ActionContext.tool_call:type_name -> assembly.policy.v1.ToolCallContext
	5,  // 5: assembly.policy.v1.ActionContext.file_op:type_name -> assembly.policy.v1.FileOpContext
	6,  // 6: assembly.policy.v1.ActionContext.network_call:type_name -> assembly.policy.v1.NetworkCallContext
	7,  // 7: assembly.policy.v1.ActionContext.process_exec:type_name -> assembly.policy.v1.ProcessExecContext
	17, // 8: assembly.policy.v1.CheckActionResponse.decision:type_name -> assembly.common.v1.Decision
	9,  // 9: assembly.policy.v1.CheckActionResponse.redact:type_name -> assembly.policy.v1.RedactInstructions
	10, // 10: assembly.policy.v1.RedactInstructions.rules:type_name -> assembly.policy.v1.RedactRule
	1,  // 11: assembly.policy.v1.BatchCheckRequest.requests:type_name -> assembly.policy.v1.CheckActionRequest
	8,  // 12: assembly.policy.v1.BatchCheckResponse.responses:type_name -> assembly.policy.v1.CheckActionResponse
	15, // 13: assembly.policy.v1.OpControlSubscribeRequest.agent_id:type_name -> assembly.common.v1.AgentId
	0,  // 14: assembly.policy.v1.OpControlMessage.signal:type_name -> assembly.policy.v1.OpControlSignal
	1,  // 15: assembly.policy.v1.PolicyService.CheckAction:input_type -> assembly.policy.v1.CheckActionRequest
	11, // 16: assembly.policy.v1.PolicyService.BatchCheck:input_type -> assembly.policy.v1.BatchCheckRequest
	13, // 17: assembly.policy.v1.PolicyService.OpControlStream:input_type -> assembly.policy.v1.OpControlSubscribeRequest
	8,  // 18: assembly.policy.v1.PolicyService.CheckAction:output_type -> assembly.policy.v1.CheckActionResponse
	12, // 19: assembly.policy.v1.PolicyService.BatchCheck:output_type -> assembly.policy.v1.BatchCheckResponse
	14, // 20: assembly.policy.v1.PolicyService.OpControlStream:output_type -> assembly.policy.v1.OpControlMessage
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_policy_proto_init() }
func file_policy_proto_init() {
	if File_policy_proto != nil {
		return
	}
	file_common_proto_init()
	file_policy_proto_msgTypes[1].OneofWrappers = []any{
		(*ActionContext_LlmCall)(nil),
		(*ActionContext_ToolCall)(nil),
		(*ActionContext_FileOp)(nil),
		(*ActionContext_NetworkCall)(nil),
		(*ActionContext_ProcessExec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_proto_goTypes,
		DependencyIndexes: file_policy_proto_depIdxs,
		EnumInfos:         file_policy_proto_enumTypes,
		MessageInfos:      file_policy_proto_msgTypes,
	}.Build()
	File_policy_proto = out.File
	file_policy_proto_goTypes = nil
	file_policy_proto_depIdxs = nil
}
