// Code generated by scripts/gen-metadata.go. DO NOT EDIT.
//
// To regenerate, run `go generate ./...` from the repo root. See
// metadata/sdk.yaml and go.mod for the authoritative source values.

package version

// ModulePath is the canonical Go import path for this SDK, sourced from
// go.mod. Consumers that need to construct a self-referential URL (e.g. an
// error message pointing users at the repo) should read this constant
// instead of hard-coding the string.
const ModulePath = "github.com/ai-agent-assembly/go-sdk"

// ProtocolVersion is the gateway wire-protocol version this SDK build is
// pinned to, sourced from the top-level VERSION file. It is the value the
// gateway is expected to advertise on Init handshakes.
const ProtocolVersion = "0.0.1-rc.4"

// DocsURL is the canonical documentation site for the Go SDK.
const DocsURL = "https://docs.agent-assembly.com/go-sdk/"

// RepoURL is the canonical GitHub repository URL for the Go SDK.
const RepoURL = "https://github.com/ai-agent-assembly/go-sdk"
