/* Generated by cbindgen — do not edit by hand. See aa-ffi-go/cbindgen.toml. */

#ifndef AA_FFI_GO_H
#define AA_FFI_GO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Opaque handle to an active Agent Assembly session.

 Wraps a shared [`AssemblyClient`]. Created by [`aa_connect`]; released by
 [`aa_disconnect`]. Opaque to C — go-sdk holds it as a `*aa_client_handle`.
 */
typedef struct aa_client_handle aa_client_handle;

/*
 C-ABI status code returned by every fallible entry point.
 */
typedef int32_t AaStatus;

/*
 C-ABI policy decision returned by [`aa_query_policy`].

 Mirrors `aa_proto::assembly::common::v1::Decision`. `UNSPECIFIED` is folded
 onto `ALLOW` so an unset/garbled decision never silently blocks.
 */
typedef int32_t AaDecision;

#define AA_STATUS_OK 0

#define AA_STATUS_NULL_POINTER 1

#define AA_STATUS_INVALID_UTF8 2

/*
 The client has been shut down (or its background IPC thread has exited).
 */
#define AA_STATUS_NOT_CONNECTED 3

#define AA_STATUS_MUTEX_POISONED 4

/*
 The background IPC thread could not be spawned.
 */
#define AA_STATUS_IPC_ERROR 5

/*
 The IPC command channel is closed, so the event could not be enqueued.
 */
#define AA_STATUS_CHANNEL_CLOSED 6

/*
 A panic was caught at the FFI boundary (never propagated across it).
 */
#define AA_STATUS_PANIC 7

/*
 The gateway gRPC endpoint could not be reached for registration. Unlike a
 policy query, [`aa_register`] is **fail-closed** — it surfaces this rather
 than silently proceeding without a credential token.
 */
#define AA_STATUS_GATEWAY_UNREACHABLE 8

/*
 The gateway was reached but rejected the `Register` call (e.g. an invalid
 `did:key`). [`aa_register`] surfaces it; registration never fails open.
 */
#define AA_STATUS_REGISTER_FAILED 9

/*
 Action permitted. A failed query no longer maps to allow — it surfaces a
 non-OK status instead (see [`aa_query_policy`]).
 */
#define AA_DECISION_ALLOW 0

/*
 Action blocked.
 */
#define AA_DECISION_DENY 1

/*
 Action held for human approval.
 */
#define AA_DECISION_PENDING 2

/*
 Action permitted but sensitive fields must be redacted first.
 */
#define AA_DECISION_REDACT 3

/*
 No decision rendered (proto3 zero value `UNSPECIFIED`). Not an authoritative
 allow — the Go layer maps it through its fail-closed path under enforce
 (AAASM-4166), so it must not alias `AA_DECISION_ALLOW`.
 */
#define AA_DECISION_UNSPECIFIED 4

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Open a session to the runtime over the Unix socket at `endpoint`.

 On success, `*out_client` receives an owned handle that must be released
 with [`aa_disconnect`].

 `agent_id` is the agent identity the background thread signs the runtime
 session handshake with (AAASM-3587); it may be null. `sdk_version` is the
 user-facing Go-module SDK version the binding forwards so it — not the shared
 `aa-sdk-client` crate version — is what gets signed into the handshake proof
 (AAASM-3683); null falls back to the crate version (no regression vs
 AAASM-3666).

 # Safety

 `endpoint` must be a valid NUL-terminated C string; `agent_id` and
 `sdk_version` must each be a valid NUL-terminated C string or null;
 `out_client` must be a valid, writable pointer to a `*mut aa_client_handle`.
 */
AaStatus aa_connect(const char *endpoint,
                    const char *agent_id,
                    const char *sdk_version,
                    aa_client_handle **out_client);

/*
 Register this agent with the governance gateway and store the issued
 credential token on the session.

 Delegates to [`AssemblyClient::register`] — the SDK's only direct gateway
 gRPC call (ADR 0004). It hits `AgentLifecycleService.Register`; the returned
 `credential_token` is held by the shared client and attached to every later
 [`aa_query_policy`] so the gateway's `validate_credential_token` does not
 deny a registered agent. On success `*out_policy_id` receives the
 gateway-assigned policy id as an owned, NUL-terminated string the caller must
 release with [`aa_free_string`].

 # Fail-closed

 Unlike [`aa_query_policy`], registration is **not** advisory: a failure
 surfaces rather than failing open. `AA_STATUS_GATEWAY_UNREACHABLE` means the
 gateway gRPC endpoint could not be reached; `AA_STATUS_REGISTER_FAILED` means
 the gateway rejected the call (e.g. an invalid `did:key`). `*out_policy_id`
 is left untouched on any non-`AA_STATUS_OK` return.

 # Arguments

 * `agent_id` — the agent identity to register (derived into a `did:key` +
   Ed25519 public key by the shared client).
 * `name` / `framework` — descriptive metadata the gateway records.
 * `gateway_endpoint` — the gRPC endpoint (e.g. `"http://127.0.0.1:50051"`);
   may be null to let the shared client resolve it from `AA_GATEWAY_ENDPOINT`
   or its default.
 * `team_id` / `parent_agent_id` — the agent's lineage/team scoping forwarded
   to the gateway on the native register (AAASM-3415, mirroring the pyo3/napi
   shims): `team_id` drives team-budget attribution and `parent_agent_id` the
   topology graph. Both are optional — null leaves the agent team-unscoped /
   root.

 # Safety

 `client` must be a handle from [`aa_connect`] that has not been
 disconnected. `agent_id`, `name`, and `framework` must be valid
 NUL-terminated C strings. `gateway_endpoint`, `team_id`, and
 `parent_agent_id` must each be a valid NUL-terminated C string or null.
 `out_policy_id` must be a valid, writable pointer.
 */
AaStatus aa_register(aa_client_handle *client,
                     const char *agent_id,
                     const char *name,
                     const char *framework,
                     const char *gateway_endpoint,
                     const char *team_id,
                     const char *parent_agent_id,
                     char **out_policy_id);

/*
 Report an audit event `(event_type, details)` to the runtime.

 Delegates to [`AssemblyClient::report_event`]; `details` passes through the
 advisory preflight before shipping, and the runtime re-scans regardless.

 # Safety

 `client` must be a handle from [`aa_connect`] that has not been
 disconnected; `event_type` and `details` must be valid NUL-terminated C
 strings.
 */
AaStatus aa_send_event(aa_client_handle *client, const char *event_type, const char *details);

/*
 Synchronously query the runtime for a policy decision on an action.

 Builds a `CheckActionRequest` from the supplied inputs, sends it to the
 runtime over the shared session, and blocks (up to the shared client's 5 s
 timeout) for the decision. Delegates entirely to
 [`AssemblyClient::query_policy`]; this shim only marshals across the C
 boundary.

 On success, `*out_decision` receives an [`AaDecision`] and `*out_reason`
 receives an owned, NUL-terminated reason string the caller must release with
 [`aa_free_string`] (always non-null on `AA_STATUS_OK`, even when empty).

 # Fail-closed signalling

 The SDK is **advisory, not authoritative**, but this shim must not silently
 turn a failed query into an allow (AAASM-3920). If the runtime fails to return
 a decision — a timeout, an unreachable runtime, or a closed session — this
 returns a **non-OK status** (`AA_STATUS_NOT_CONNECTED` for a timeout or
 shut-down session, `AA_STATUS_CHANNEL_CLOSED` for an exited IPC thread,
 `AA_STATUS_MUTEX_POISONED` for an internal poisoned lock) and leaves the
 out-params untouched. The Go layer maps the status to an error so the tool
 wrapper applies its fail-open / fail-closed posture (deny under the default
 enforce). The runtime / proxy / eBPF layers remain authoritative.

 # Arguments

 * `agent_id` — the calling agent's own id (the `agent_id.agent_id` field).
 * `action_type` — snake_case proto action name (e.g. `"tool_call"`,
   `"llm_call"`); unknown values fall back to `tool_call`.
 * `tool_name` — registered tool name; may be null. Used for `tool_call` /
   `tool_result` actions and as the model for `llm_call`.
 * `args_json` — JSON-encoded argument map; may be null. Carried as the tool
   `args_json` bytes for tool actions.

 # Safety

 `client` must be a handle from [`aa_connect`] that has not been
 disconnected. `agent_id` and `action_type` must be valid NUL-terminated C
 strings. `tool_name` and `args_json` must each be a valid NUL-terminated C
 string or null. `out_decision` and `out_reason` must be valid, writable
 pointers.
 */
AaStatus aa_query_policy(aa_client_handle *client,
                         const char *agent_id,
                         const char *action_type,
                         const char *tool_name,
                         const char *args_json,
                         AaDecision *out_decision,
                         char **out_reason);

/*
 Shut down the session and free the handle.

 Blocks on the background IPC thread's join (the shared client signals it).
 After this call the handle is freed and must not be reused.

 # Safety

 `client` must be a handle previously returned by [`aa_connect`] and not yet
 disconnected.
 */
AaStatus aa_disconnect(aa_client_handle *client);

/*
 Free a C string previously handed out by this crate.

 Retained as a stable ABI helper for C callers; the event API no longer
 returns owned strings.

 # Safety

 `value` must be a pointer previously returned by this crate, or null.
 */
void aa_free_string(char *value);

/*
 Free a byte buffer previously handed out by this crate.

 # Safety

 `bytes`/`len` must originate from an allocation owned by this crate, or
 `bytes` may be null.
 */
void aa_free_bytes(uint8_t *bytes, uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AA_FFI_GO_H */
