/* Generated by cbindgen — do not edit by hand. See aa-ffi-go/cbindgen.toml. */

#ifndef AA_FFI_GO_H
#define AA_FFI_GO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Opaque handle to an active Agent Assembly session.

 Wraps a shared [`AssemblyClient`]. Created by [`aa_connect`]; released by
 [`aa_disconnect`]. Opaque to C — go-sdk holds it as a `*aa_client_handle`.
 */
typedef struct aa_client_handle aa_client_handle;

/*
 C-ABI status code returned by every fallible entry point.
 */
typedef int32_t AaStatus;

#define AA_STATUS_OK 0

#define AA_STATUS_NULL_POINTER 1

#define AA_STATUS_INVALID_UTF8 2

/*
 The client has been shut down (or its background IPC thread has exited).
 */
#define AA_STATUS_NOT_CONNECTED 3

#define AA_STATUS_MUTEX_POISONED 4

/*
 The background IPC thread could not be spawned.
 */
#define AA_STATUS_IPC_ERROR 5

/*
 The IPC command channel is closed, so the event could not be enqueued.
 */
#define AA_STATUS_CHANNEL_CLOSED 6

/*
 A panic was caught at the FFI boundary (never propagated across it).
 */
#define AA_STATUS_PANIC 7

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Open a session to the runtime over the Unix socket at `endpoint`.

 On success, `*out_client` receives an owned handle that must be released
 with [`aa_disconnect`].

 # Safety

 `endpoint` must be a valid NUL-terminated C string; `out_client` must be a
 valid, writable pointer to a `*mut aa_client_handle`.
 */
AaStatus aa_connect(const char *endpoint, aa_client_handle **out_client);

/*
 Report an audit event `(event_type, details)` to the runtime.

 Delegates to [`AssemblyClient::report_event`]; `details` passes through the
 advisory preflight before shipping, and the runtime re-scans regardless.

 # Safety

 `client` must be a handle from [`aa_connect`] that has not been
 disconnected; `event_type` and `details` must be valid NUL-terminated C
 strings.
 */
AaStatus aa_send_event(aa_client_handle *client, const char *event_type, const char *details);

/*
 Shut down the session and free the handle.

 Blocks on the background IPC thread's join (the shared client signals it).
 After this call the handle is freed and must not be reused.

 # Safety

 `client` must be a handle previously returned by [`aa_connect`] and not yet
 disconnected.
 */
AaStatus aa_disconnect(aa_client_handle *client);

/*
 Free a C string previously handed out by this crate.

 Retained as a stable ABI helper for C callers; the event API no longer
 returns owned strings.

 # Safety

 `value` must be a pointer previously returned by this crate, or null.
 */
void aa_free_string(char *value);

/*
 Free a byte buffer previously handed out by this crate.

 # Safety

 `bytes`/`len` must originate from an allocation owned by this crate, or
 `bytes` may be null.
 */
void aa_free_bytes(uint8_t *bytes, uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AA_FFI_GO_H */
