// Code generated by scripts/gen-metadata.go. DO NOT EDIT.
//
// To regenerate, run `go generate ./...` from the repo root. The value
// is sourced from the top-level VERSION file (same source as
// internal/version.ProtocolVersion) — edit VERSION, not this file.

package assembly

// Version is the published version of the agent-assembly Go SDK.
//
// Pre-release values follow the SemVer pre-release identifier form
// (`MAJOR.MINOR.PATCH-alpha.N`). The git tag mirrors this with a
// leading `v` (e.g. `v0.0.1-alpha.1`).
const Version = "0.0.1-rc.4"
