//go:build ignore

// Go SDK quick-start per-framework tabs generator. Epic AAASM-4511 / AAASM-4515.
//
// Renders the hextra `{{< tabs >}}` block for the "Govern your first agent" step
// of docs/quick-start.md from vendored, drift-checked source data:
//
//   - metadata/quickstart/manifest.json — the data-driven tab index. Its
//     `quickstart_tabs` list (framework_ids, in display order) selects and
//     orders which `frameworks[]` entries become tabs; the tab label is the
//     entry's `label`.
//   - metadata/quickstart/_snippets/<framework_id>.go.txt — the extracted
//     `quickstart` region (the WrapTools + wiring slice) copied verbatim from
//     the runnable examples. The tab body is a fenced Go code block of this
//     content, byte-for-byte.
//
// The program rewrites only the bounded block
//
//	<!-- BEGIN GENERATED: quickstart-tabs -->
//	...
//	<!-- END GENERATED: quickstart-tabs -->
//
// in docs/quick-start.md, preserving every byte of surrounding hand-written
// prose. It has zero network access and reads only local repo state — the
// examples repo is never fetched at build time; the vendored copy is the source
// of truth, kept honest by the `go generate ./...` + `git diff` drift check in
// .github/workflows/docs-metadata.yml.
//
// Invocation (from repo root):
//
//	go run scripts/gen-quickstart-tabs.go
//
// The `//go:build ignore` tag keeps this file out of `go build ./...`.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// framework mirrors one entry of manifest.json `frameworks[]`. Only the fields
// consumed by the generator are declared.
type framework struct {
	FrameworkID   string `json:"framework_id"`
	Label         string `json:"label"`
	Status        string `json:"status"`
	Lang          string `json:"lang"`
	SnippetPath   string `json:"snippet_path"`
	SourceExample string `json:"source_example"`
}

// manifest mirrors metadata/quickstart/manifest.json.
type manifest struct {
	SchemaVersion  int         `json:"schema_version"`
	SDK            string      `json:"sdk"`
	Source         string      `json:"source"`
	QuickstartTabs []string    `json:"quickstart_tabs"`
	Frameworks     []framework `json:"frameworks"`
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("gen-quickstart-tabs: ")

	repoRoot, err := findRepoRoot()
	if err != nil {
		log.Fatalf("resolve repo root: %v", err)
	}

	m, err := loadManifest(repoRoot)
	if err != nil {
		log.Fatalf("load manifest: %v", err)
	}

	block, err := renderTabsBlock(repoRoot, m)
	if err != nil {
		log.Fatalf("render tabs block: %v", err)
	}

	if err := rewriteQuickStartBlock(repoRoot, block); err != nil {
		log.Fatalf("rewrite docs/quick-start.md tabs block: %v", err)
	}
}

// findRepoRoot walks up from the working directory until it finds go.mod, so the
// generator works both when invoked directly from the repo root and by
// `go generate` from a nested package directory.
func findRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}
	dir := cwd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found in %s or any parent", cwd)
		}
		dir = parent
	}
}

func loadManifest(repoRoot string) (manifest, error) {
	path := filepath.Join(repoRoot, "metadata", "quickstart", "manifest.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		return manifest{}, fmt.Errorf("read %s: %w", path, err)
	}
	var m manifest
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&m); err != nil {
		return manifest{}, fmt.Errorf("parse manifest.json: %w", err)
	}
	if len(m.QuickstartTabs) == 0 {
		return manifest{}, fmt.Errorf("manifest.json: quickstart_tabs is empty")
	}
	return m, nil
}

// byID indexes frameworks by framework_id for quickstart_tabs lookup.
func byID(m manifest) map[string]framework {
	idx := make(map[string]framework, len(m.Frameworks))
	for _, f := range m.Frameworks {
		idx[f.FrameworkID] = f
	}
	return idx
}

// renderTabsBlock builds the bounded generated region: a hextra tabs shortcode
// with one tab per quickstart_tabs id, each body a fenced Go code block of the
// vendored snippet. Uses the current hextra (v0.12.x) per-tab `name=` form; the
// legacy `items=` form on {{< tabs >}} is deprecated and emits a build warning.
func renderTabsBlock(repoRoot string, m manifest) (string, error) {
	idx := byID(m)

	var b strings.Builder
	b.WriteString("<!-- BEGIN GENERATED: quickstart-tabs -->\n")
	b.WriteString("<!-- GENERATED BY scripts/gen-quickstart-tabs.go — DO NOT EDIT. -->\n")
	b.WriteString("<!-- Source data: metadata/quickstart/ (vendored from the examples repo). -->\n")
	b.WriteString("{{< tabs >}}\n")

	for _, id := range m.QuickstartTabs {
		f, ok := idx[id]
		if !ok {
			return "", fmt.Errorf("quickstart_tabs references unknown framework_id %q", id)
		}
		snippetPath := filepath.Join(repoRoot, filepath.FromSlash(f.SnippetPath))
		snippet, err := os.ReadFile(snippetPath)
		if err != nil {
			return "", fmt.Errorf("read snippet for %q: %w", id, err)
		}
		code := strings.TrimRight(string(snippet), "\n")

		fmt.Fprintf(&b, "{{< tab name=%q >}}\n", f.Label)
		b.WriteString("\n")
		fmt.Fprintf(&b, "_Governance slice from the runnable `%s` example._\n\n", f.SourceExample)
		b.WriteString("```go\n")
		b.WriteString(code)
		b.WriteString("\n```\n\n")
		b.WriteString("{{< /tab >}}\n")
	}

	b.WriteString("{{< /tabs >}}\n")
	b.WriteString("<!-- END GENERATED: quickstart-tabs -->")
	return b.String(), nil
}

// quickStartBlockRE matches the entire bounded block (including sentinels) so the
// generator replaces it in-place without touching surrounding prose.
var quickStartBlockRE = regexp.MustCompile(
	`(?s)<!--\s*BEGIN GENERATED: quickstart-tabs\s*-->.*?<!--\s*END GENERATED: quickstart-tabs\s*-->`,
)

func rewriteQuickStartBlock(repoRoot, block string) error {
	target := filepath.Join(repoRoot, "docs", "quick-start.md")
	current, err := os.ReadFile(target)
	if err != nil {
		return fmt.Errorf("read quick-start.md: %w", err)
	}
	if !quickStartBlockRE.Match(current) {
		return fmt.Errorf(
			"docs/quick-start.md is missing the quickstart-tabs generated block; " +
				"add a `<!-- BEGIN GENERATED: quickstart-tabs -->` / " +
				"`<!-- END GENERATED: quickstart-tabs -->` pair to opt in",
		)
	}
	updated := quickStartBlockRE.ReplaceAllLiteral(current, []byte(block))
	if bytes.Equal(current, updated) {
		return nil
	}
	return os.WriteFile(target, updated, 0o644)
}
